addon-data-url=https://addons.ddev.com/addons.json 
developer-mode=false 
fail-on-hook-fail=false 
instrumentation-opt-in=true 
instrumentation-queue-size=0 
instrumentation-reporting-interval=0s 
instrumentation-user= 
internet-detection-timeout-ms=3000 
last-started-version=v1.25.1 
letsencrypt-email= 
mailpit-http-port=8025 
mailpit-https-port=8026 
mkcert-caroot=/home/gustavo/.local/share/mkcert 
no-bind-mounts=false 
no-tui=false 
omit-containers=[] 
omit-project-name-by-default=false 
performance-mode=none 
project-tld=ddev.site 
remote-config-update-interval=0 
remote-config-url=https://raw.githubusercontent.com/ddev/remote-config/main/remote-config.jsonc 
required-docker-compose-version=v5.0.2 
router-bind-all-interfaces=true 
router-http-port=80 
router-https-port=443 
share-default-provider= 
simple-formatting=false 
sponsorship-data-url=https://ddev.com/s/sponsorship-data.json 
table-style=default 
traefik-monitor-port=10999 
use-docker-compose-from-path=false 
use-hardened-images=false 
use-letsencrypt=false 
wsl2-no-windows-hosts-mgt=false 
xdebug-ide-location= 
xhgui-http-port=8143 
xhgui-https-port=8142 
xhprof-mode=xhgui 
